# Generated by Django 4.1.3 on 2022-11-30 22:39

import authentication.models
import authentication.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=authentication.models.generate_uuid, editable=False, unique=True, verbose_name='Business identifier')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('public_key', models.TextField(blank=True, max_length=1024, null=True, validators=[authentication.validators.KeyValidator()], verbose_name='Public key')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this business should be treated as active. Unselect this instead of deleting businesses.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'business',
            },
        ),
    ]
